version: '3'
services:
  web:
    image: api-service
    build: .
    command: "node src/server.js"
    ports:
      - "8000:8000"
    depends_on:
      - "mongo"
      - "redis"
  mongo:
    image: "mongo"
    container_name: "mongo"
    logging:
      driver: "none"
    ports:
      - "27017:27017"
  redis:
    image: "redis"
    container_name: "redis"
    ports:
      - "6379:6379"


